global:
  resolve_timeout: 5m

route:
  receiver: 'web.hook'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: '${DISCORD_WEBHOOK_URL}'